"""add simulation runs and events

Revision ID: 208fae8bb35d
Revises: a6eb371530ad
Create Date: 2026-05-19 09:56:04.832882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '208fae8bb35d'
down_revision: Union[str, Sequence[str], None] = 'a6eb371530ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('scenario_name', sa.String(length=120), nullable=False),
    sa.Column('parameters_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_failed_assets', sa.Integer(), nullable=False),
    sa.Column('critical_assets_failed', sa.Integer(), nullable=False),
    sa.Column('failed_asset_percentage', sa.Float(), nullable=False),
    sa.Column('max_cascade_depth', sa.Integer(), nullable=False),
    sa.Column('earliest_failure_minute', sa.Integer(), nullable=False),
    sa.Column('latest_failure_minute', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('criticality', sa.Float(), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('time_minute', sa.Integer(), nullable=False),
    sa.Column('caused_by_asset_id', sa.String(length=64), nullable=True),
    sa.Column('dependency_type', sa.String(length=50), nullable=True),
    sa.Column('propagation_strength', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulation_events')
    op.drop_table('simulation_runs')
    # ### end Alembic commands ###
