"""add scenarios table

Revision ID: a6eb371530ad
Revises: 57f161de28c6
Create Date: 2026-05-18 19:10:18.488362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6eb371530ad'
down_revision: Union[str, Sequence[str], None] = '57f161de28c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('scenario_type', sa.Enum('GRID_FAILURE', 'COMPONENT_FAILURE', 'COMMON_MODE_FAILURE', 'CYBER_EVENT', 'NATURAL_HAZARD', name='scenario_type'), nullable=False),
    sa.Column('initial_failed_asset_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('propagation_threshold', sa.Float(), nullable=False),
    sa.Column('max_time_minutes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenarios')
    # ### end Alembic commands ###
